### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.5

### PR DESCRIPTION
**Pull request by rvalieris**

### CODE REVIEW

**Comment by jdblischak** [comment]
@rvalieris Just a heads up. I suspect there will be lots of missing builds for the assertive.* packages because they are all added together in a big PR to staged-recipes https://github.com/conda-forge/staged-recipes/pull/4678

**Comment by rvalieris** [comment]
ah yes. thanks for the link, I will try to do dependencies first.

**Comment by jenzopr** [comment]
Can I help with something?

**Comment by jdblischak** [comment]
@jenzopr Thanks for offering! You'll need to coordinate with @rvalieris to avoid duplicating effort.

According to a script I have, the following 4 r-assertive.* feedstocks need to be rerendered and have all their dependencies available:

* r-assertive.matrices
* r-assertive.models
* r-assertive.numbers
* r-assertive.properties

More may become ready to be rerendered once these ones are updated.

**Comment by rvalieris** [comment]
yes, basically all I am doing is re-rendering feedstocks that are missing some builds, feel free to join in. the effort is mostly forking the repos and running conda-smithy.

**Comment by jenzopr** [comment]
Lets see what I can do. For now, I started r-assertive.numbers as a trial :)

**Pull request merged**
